### ISSUE TITLE
Mysql Connector multiple databases

### ISSUE THREAD

**Issue by jquintero33** [SteeltoeOSS/Connectors#13]
Does the MySqlConnector support binding to more than one database?

**Comment by TimHess** [comment]
@jquintero33 the MySql Connector does not currently support binding more than one database. Could you provide a little more context around how you would like that functionality to work?

**Comment by TimHess** [comment]
Re-reading my original answer, I should note that it was not technically correct. Steeltoe connectors have always supported binding more than one instance of any given service, you just have to use the methods that specify the binding name when you add them to the DI container.

The real problem has been getting them back out of the container.. this is not a complete solution, but the [MySQL EFCore sample](https://github.com/SteeltoeOSS/Samples/tree/dev/Connectors/src/AspDotNetCore/MySqlEFCore) has been updated to work with multiple databases. This type of example would work with any of the EntityFramework variants since we can request which DbContext we want.

It is worth noting that this is a limitation of the way Microsoft Dependency Injection works -- by that I'm referring to the inability to qualify which instance of type X you're requesting:
```csharp
// eg: How do I specify WHICH MySqlConnection I want here?
public IActionResult MySqlData([FromServices] MySqlConnection dbConnection)
```

**Comment by jkonicki** [comment]
Closing issue.  Please reopen under the `steeltoe` repository if still an issue.
