### ISSUE TITLE
Unclosed connection in Redis and RabbitMQ health check

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Connectors#29]

**Comment by TimHess** [comment]
@VenkateshSrini, Thanks for reporting, this is a significant find.
[This commit](https://github.com/SteeltoeOSS/Connectors/commit/77f652456d0af0d306b67e33c629b678da562812) should resolve the RabbitMQ issue - can you provide any more information on symptoms you're seeing with Redis?

**Comment by VenkateshSrini** [comment]
@TimHess ,
**RabbitMQ**
I still feel reflection operation is a costly one for health check. As far as I feel, the health check should be the least expensive operation in terms as possible. So I suggest that you use strongly typed variables instead of reflection. In ways there is a reference RabbitMQ.Client in the SteelToe ConnectorBase

**Redis**
In Redis also we are seeing a large number of connection open. The COnnectionMultiplexer that is created using the RedisFactor.Create(null) needs to be disposed. This would be simple if you a strongly typed coding instead of assembly. For StackExchange redis, still the stackexchange.redis,strongname assemblies are only used. In the connection factor we still have the namespace declaration and some strongly typed code. So I do not see a rational in using the reflection. If you are still seeing a value in reflection then please close the connection



 
            }


 
            catch (Exception e)


 
            {
 `

**Comment by TimHess** [comment]
I understand the sentiment around using reflection, but it is used in this library for licensing-related reasons and to allow flexibility (eg: you can choose between StackExchange.Redis and Microsoft.Extensions.Caching, or choose between available MySQL drivers, etc)

The guidance on the StackExchange library is that the ConnectionMultiplexer should not be disposed, but rather kept around, as it is expensive to open that connection. When you say a large number of connections, is that an increasing number over time, or just more than expected? What is a large number? I've updated the Steeltoe ASP.NET Core Redis Connector sample to add the health check and I'm not seeing significant issues with it.

Also, StackExchange.Redis 2.x resolved a number of performance issues, but the .Strongname version has been discontinued. What version of StackExchange.Redis are you using?

**Comment by VenkateshSrini** [comment]
We are using Microsoft.Extension.Caching library as that is the one recommended from Microsoft. Also we use the AddDistributedCache interfaces and hence cannot replace it easily with StackExchange.Redis.

If connection multiplxer is not disposed in health check then lots of connection get created to redis. You can try in a ASP.NET core application with huge number of hits to redis. The huge number I talk is close to 5 lakhs. The connection increase over a period of time. The issue will manifest by saying HSET or HGET operation timed out and basically when you see the log of VM that holds the redis, the ops say there are huge number of connection.

Just to confirm the same is caused by the Redis we commented the health check and every thing came back to normal. 

We are using the StrongName version as we are tied to Microsoft.Extensions.Caching.Redis.

**Comment by TimHess** [comment]
Aha! Thanks for the additional information - I understand what is happening now. When the health check fails, we remove references to a couple objects without actually cleaning them up. This results in a zombie ConnectionMultiplexer (and corresponding open Redis connection) for every failed health check.

I wasn't seeing anything initially because I was only testing that we weren't opening a new connection every time under normal circumstances. It took testing under _significantly_ greater load to cause the kind of failure you were seeing.

The update I just pushed resolves the open connection issue as far as I can tell, could you test it out to see if it works for you? It's available on the [dev feed](https://www.myget.org/F/steeltoedev/api/v3/index.json) in version 2.2.0-dev-00355, you can use it straight out of this branch https://github.com/SteeltoeOSS/Connectors/tree/update21x or I can build you a package if you'd like.

Finally, yes, that announcement is what I was referring to - in my testing, on this issue in particular, 2.2 is **significantly** faster. I don't think there's a way to use the new StackExchange.Redis package and Microsoft Caching on AspNetCore 2.1

**Comment by VenkateshSrini** [comment]
Hey I would not be able to test this as I observed this for a client who does huge data processing app. Like I did for RabbitMQ client can you also put the commit link so that I can review the fix. Also in one of the discussion I understand that RabbitMQ comes with a Management URI connection pinging which we can know the health status rather than actually opening an amqp connection and check. Can we change to this approach

**Comment by TimHess** [comment]
This was the commit, there's not much to see: https://github.com/SteeltoeOSS/Connectors/commit/882068c09eb08fd757d532ed1ddbe82104c6a6dd

With regard to changing the way the health check works, I would think that it is most valuable to validate that the connection we're intending to use is working. In this case I would think that a ping to prove the host is up is not as complete as opening an AMQP connection - what if the host is up, but the RabbitMQ process is down? In that event we'd have a false positive on the health reporting.

**Comment by VenkateshSrini** [comment]
Hi,
I have left a commit saying that can you call the dispose method instead. 
Regarding the using the RabbitMQ, I had a discussion with Pivotal platform team. They suggested we use RabbitMQ management API instead of opening and closing the connection. They say that such a check actually increases the connection churn. That is why I asked this question

**Comment by TimHess** [comment]
As far as I know, the RabbitMQ.Client doesn't know anything about the management API. Additionally, I don't know that Steeltoe is yet parsing the management info from VCAP_SERVICES. The idea of using the management API is interesting, but would involve rework that we do not currently have on our roadmap. If it is of interest to you, we'd welcome a pull request.

At this point, I believe both of the problem areas you raised have been fixed, so I'm going to close this issue. If there are still hanging connections after these changes, please reopen this issue. If you still feel strongly on changing the RabbitMQ health check implementation, please open a new issue for that with more specific detail on what you'd like to see (and ideally a future pull request).

**Comment by TimHess** [comment]
Steeltoe is parsing VCAP_SERVICES, just not the management section (which is provided separately) of a RabbitMQ service binding.

**Comment by VenkateshSrini** [comment]
>           Steeltoe is parsing VCAP_SERVICES, just not the management section (which is provided separately) of a RabbitMQ service binding.

Hmm.. Understood. So the better option will be is to not to depend on the steeltoe credential parsing. So the better idea will be is to come up with another class, maybe, RabbitMQHealthCheck2, which will accept IConfiguration as a parameter. Then we can use the Steel.Extension.Configuration and get the RabbitMQ by querying on the tag. Post that get the management endpoint and the health check (UP or DOWN) will be based on that outcome.

**Comment by TimHess** [comment]
I'm going to caveat the rest of my response with a comment that we are still planning on looking into adding compatibility for [Microsoft's new health check option](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2) for our 2.2 release, so any further work here may not be the most valuable use of time. Following through those docs, you may note references to the BeatPulse collection of health checks. BeatPulse also includes a [RabbitMQ health check that opens a connection](https://github.com/Xabaril/BeatPulse/blob/master/src/BeatPulse.RabbitMQ/RabbitMQLiveness.cs).

In the event you are still interested in this work, my current thinking is that it would be better to enhance Steeltoe to also parse the management info since the credentials themselves will probably still be required for the health check. Walking through this test may help show what would need to be enhanced: https://github.com/SteeltoeOSS/Connectors/blob/dev/test/Steeltoe.CloudFoundry.ConnectorBase.Test/Services/RabbitMQServiceInfoFactoryTest.cs#L159

If that approach turns out to be messy or too complex, it might make sense to take advantage of this new functionality in Steeltoe.Configuration https://github.com/SteeltoeOSS/Configuration/issues/40#issuecomment-453857339

Regardless of the implementation details

**Comment by VenkateshSrini** [comment]
@TimHess ,
You read my mind here. I was also going to ask about the same. I wanted to simulate the beatpulse with Management end point of RabitMQ. But I would suggest that you should not take the .NET core 2.2 version and if you take also you need to hold on the release till .NET core 3.0. The reason for this .NET core 2.2 is not LTS. When 3.0 gets released Microsoft will quickly make .NET core 2.2 end of life. So keeping the long time objectives in mind, please consider these thoughts also
